Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -40,5 +40,18 @@ jobs:
       - name: Grant execute permissions to wait-for-it.sh
         run: chmod +x ./scripts/wait-for-it.sh
 
+      - name: Grant execute permissions to run-integration.sh
+        run: chmod +x ./scripts/run-integration.sh
+
       - name: Run integration script
         run: npm run test:integration
+        env:
+          CI: true
+
+      - name: Check test results
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Tests failed"
+            exit 1
+          fi
+
